// preload.js
(function preloadUsers() {
  if (localStorage.getItem("preloaded") === "true") return;

  const accounts = [
    {
      username: "dhamu",
      email: "dhamu@gmail.com",
      password: "dhamu123",
      first_name: "Dhashamoolam",
      last_name: "Dhamu",
      dob: "1995-01-01",
      address: "Chennai",
      aadhar: "1111-2222-3333",
      phone: "9876543210",
      account_type: "savings",
      deposit: "10000",
      createdAt: new Date().toISOString()
    },
    {
      username: "batmon",
      email: "batmon@gmail.com",
      password: "batmon123",
      first_name: "Bat",
      last_name: "Mon",
      dob: "1993-05-12",
      address: "Gotham",
      aadhar: "4444-5555-6666",
      phone: "9876501234",
      account_type: "zero_balance",
      deposit: "5000",
      createdAt: new Date().toISOString()
    },
    {
      username: "abhishek",
      email: "abhishek@gmail.com",
      password: "abhishek123",
      first_name: "Abhishek",
      last_name: "G",
      dob: "2000-08-22",
      address: "Bangalore",
      aadhar: "7777-8888-9999",
      phone: "9845001122",
      account_type: "business",
      deposit: "20000",
      createdAt: new Date().toISOString()
    },
    {
      username: "sreerag",
      email: "sreerag@gmail.com",
      password: "sreerag123",
      first_name: "Sreerag",
      last_name: "Nair",
      dob: "1998-06-10",
      address: "Kerala",
      aadhar: "4000-1111-2222",
      phone: "9995567890",
      account_type: "savings",
      deposit: "7000",
      createdAt: new Date().toISOString()
    },
    {
      username: "pranesh",
      email: "pranesh@gmail.com",
      password: "pranesh123",
      first_name: "Pranesh",
      last_name: "R",
      dob: "1997-04-18",
      address: "Kerala",
      aadhar: "4001-1234-5678",
      phone: "9876112233",
      account_type: "business",
      deposit: "15000",
      createdAt: new Date().toISOString()
    },
    {
      username: "kayyum",
      email: "kayyum@gmail.com",
      password: "kayyum123",
      first_name: "Kayyum",
      last_name: "H",
      dob: "1999-12-01",
      address: "Kerala",
      aadhar: "4002-2345-6789",
      phone: "9846123456",
      account_type: "zero_balance",
      deposit: "3000",
      createdAt: new Date().toISOString()
    },
    {
      username: "reyna",
      email: "reyna@gmail.com",
      password: "reyna123",
      first_name: "Reyna",
      last_name: "M",
      dob: "2001-03-27",
      address: "Kerala",
      aadhar: "4003-9876-5432",
      phone: "9633004455",
      account_type: "savings",
      deposit: "8500",
      createdAt: new Date().toISOString()
    },
    {
      username: "joker",
      email: "joker@gmail.com",
      password: "joker123",
      first_name: "Blind",
      last_name: "Joker",
      dob: "1995-11-11",
      address: "Kerala",
      aadhar: "4004-3333-2222",
      phone: "9876123450",
      account_type: "business",
      deposit: "9999",
      createdAt: new Date().toISOString()
    },
    {
      username: "menny",
      email: "menny@gmail.com",
      password: "menny123",
      first_name: "Menny",
      last_name: "M",
      dob: "1994-09-19",
      address: "Kerala",
      aadhar: "4005-4444-1111",
      phone: "9444002211",
      account_type: "savings",
      deposit: "10500",
      createdAt: new Date().toISOString()
    },
    {
      username: "abu",
      email: "abu@gmail.com",
      password: "abu123",
      first_name: "Abu",
      last_name: "Salim",
      dob: "1989-08-15",
      address: "Kerala",
      aadhar: "4006-5555-6666",
      phone: "9400001122",
      account_type: "zero_balance",
      deposit: "2500",
      createdAt: new Date().toISOString()
    },
    {
      username: "shajon",
      email: "shajon@gmail.com",
      password: "shajon123",
      first_name: "Shajon",
      last_name: "S",
      dob: "1990-07-07",
      address: "Kerala",
      aadhar: "4007-1212-3434",
      phone: "9447000088",
      account_type: "savings",
      deposit: "4500",
      createdAt: new Date().toISOString()
    },
    {
      username: "suraj",
      email: "suraj@gmail.com",
      password: "suraj123",
      first_name: "Suraj",
      last_name: "Venjaramood",
      dob: "1985-10-10",
      address: "Kerala",
      aadhar: "4008-9898-6767",
      phone: "9495000100",
      account_type: "business",
      deposit: "18000",
      createdAt: new Date().toISOString()
    },
    {
      username: "abul",
      email: "abul@gmail.com",
      password: "abul123",
      first_name: "Abul",
      last_name: "H",
      dob: "1992-04-22",
      address: "Kerala",
      aadhar: "4009-6543-2100",
      phone: "9988776655",
      account_type: "savings",
      deposit: "8900",
      createdAt: new Date().toISOString()
    },
    {
      username: "punya",
      email: "punya@gmail.com",
      password: "punya123",
      first_name: "Punya",
      last_name: "P",
      dob: "1996-02-10",
      address: "Kerala",
      aadhar: "4010-1122-3344",
      phone: "9876001122",
      account_type: "zero_balance",
      deposit: "4600",
      createdAt: new Date().toISOString()
    }
  ];

  localStorage.setItem("accounts", JSON.stringify(accounts));
  localStorage.setItem("preloaded", "true");
})();
